### ISSUE TITLE
List Messages response is empty

### ISSUE THREAD

**Issue by JoeBatt1989** [mailosaur/mailosaur-java#5]
I have a server that has 3 messages in and I can see the count in the List Servers API. However when I run List Messages for that server the response is returned empty. What could be the cause of this?

**Comment by hippyhorse** [comment]
Hey @JoeBatt1989 investigating this for you today - will get back to you ASAP.

**Comment by hippyhorse** [comment]
We could not reproduce this, please can you email support@mailosaur.com so we can discuss in more detail if you still have an issue
