### ISSUE TITLE
Search gives me 400s with error about server identifier

### ISSUE THREAD

**Issue by omerzach** [mailosaur/mailosaur-java#7]
Our team is using Mailosaur from JavaScript already and really enjoying it.

I'm now trying out your Java SDK from our Scala codebase and seeing some surprising results.

I can call various endpoints including `list` without issue:
```
@ (new com.mailosaur.MailosaurClient(MailosaurConstants.ApiKey)).messages.list(MailosaurConstants.ServerId).items 
res17: java.util.List[com.mailosaur.models.MessageSummary] = []
```

But if I try to `search` I get a 400 saying I'm missing a server identifier:
```
@ MailosaurClient.client.messages.search(MailosaurConstants.ServerId, new SearchCriteria()) 
com.mailosaur.MailosaurException: 400 Bad Request
{"type":"ValidationError","messages":{"criteria":"Please provide a server identifier."}}
  com.mailosaur.MailosaurClient.request(MailosaurClient.java:154)
  com.mailosaur.Messages.search(Messages.java:93)
  ammonite.$sess.cmd18$.<init>(cmd18.sc:1)
  ammonite.$sess.cmd18$.<clinit>(cmd18.sc)
```

Can you help me with this?

**Comment by omerzach** [comment]
I'm seeing this issue on both versions 5.0.0 and 6.0.0

**Comment by hippyhorse** [comment]
Hi @omerzach please can you open a support ticket by emailing support@mailosaur.com. Including an example of your code executing the `search` method (excluding any API keys).

Thanks!
